"""plans and listener

Revision ID: 013099bdb245
Revises: f139920f90ec
Create Date: 2026-06-26 17:43:45.662933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013099bdb245'
down_revision: Union[str, None] = 'f139920f90ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plan_categories',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'category_id')
    )
    # can_upload: server_default=true preenche linhas existentes; depois remove o
    # default no banco (fica no app/ORM). Usuários atuais continuam podendo enviar.
    op.add_column(
        'users',
        sa.Column('can_upload', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('users', 'can_upload', server_default=None)
    op.add_column('users', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'users', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'plan_expires_at')
    op.drop_column('users', 'plan_id')
    op.drop_column('users', 'can_upload')
    op.drop_table('plan_categories')
    op.drop_table('plans')
    # ### end Alembic commands ###
