"""baseline schema

Revision ID: 892f4e6e2e3a
Revises: 
Create Date: 2026-06-26 10:52:00.982952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892f4e6e2e3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('quota_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archives_owner_id'), 'archives', ['owner_id'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_owner_id'), 'playlists', ['owner_id'], unique=False)
    op.create_table('bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('prefix', sa.String(length=512), nullable=False),
    sa.Column('cover_name', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bands_archive_id'), 'bands', ['archive_id'], unique=False)
    op.create_table('playlist_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_share_playlist_id'), 'playlist_share', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_share_shared_with_id'), 'playlist_share', ['shared_with_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('display_name', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_band_id'), 'tracks', ['band_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_owner_id'), 'favorites', ['owner_id'], unique=False)
    op.create_index(op.f('ix_favorites_track_id'), 'favorites', ['track_id'], unique=False)
    op.create_table('play_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_history_owner_id'), 'play_history', ['owner_id'], unique=False)
    op.create_index(op.f('ix_play_history_played_at'), 'play_history', ['played_at'], unique=False)
    op.create_index(op.f('ix_play_history_track_id'), 'play_history', ['track_id'], unique=False)
    op.create_table('playlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_items_playlist_id'), 'playlist_items', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_items_track_id'), 'playlist_items', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_items_track_id'), table_name='playlist_items')
    op.drop_index(op.f('ix_playlist_items_playlist_id'), table_name='playlist_items')
    op.drop_table('playlist_items')
    op.drop_index(op.f('ix_play_history_track_id'), table_name='play_history')
    op.drop_index(op.f('ix_play_history_played_at'), table_name='play_history')
    op.drop_index(op.f('ix_play_history_owner_id'), table_name='play_history')
    op.drop_table('play_history')
    op.drop_index(op.f('ix_favorites_track_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_owner_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_tracks_band_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_playlist_share_shared_with_id'), table_name='playlist_share')
    op.drop_index(op.f('ix_playlist_share_playlist_id'), table_name='playlist_share')
    op.drop_table('playlist_share')
    op.drop_index(op.f('ix_bands_archive_id'), table_name='bands')
    op.drop_table('bands')
    op.drop_index(op.f('ix_playlists_owner_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_archives_owner_id'), table_name='archives')
    op.drop_table('archives')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
