"""user profile fields

Revision ID: f5e8f3f4cf58
Revises: 892f4e6e2e3a
Create Date: 2026-06-26 11:31:05.483496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e8f3f4cf58'
down_revision: Union[str, None] = '892f4e6e2e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # is_active: server_default=true preenche as linhas existentes; depois removemos
    # o default no nível do banco (o default fica no app/ORM).
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('users', 'is_active', server_default=None)
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_filename', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'avatar_filename')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
